using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WX.WFA.VO;

namespace WX.WFA.ServiceContract
{
    public interface IS_GZLGL
    {
        //Tuple<VO_SYS_HEAD, VO_WF_SLXXX, VO_WF_SLXXX[]> WFGL_CXSLXX(VO_WF_SLXXX vo_WF_SLXX);
        Tuple<VOX_SYS_HEAD,VOX_SYS_ERROR,VO_WF_SLXX_CX[]> WFGL_CXSLXX(VO_WF_SLXX vo_WF_SLXX);
        Tuple<VOX_SYS_HEAD, VOX_SYS_ERROR, VO_WF_SLXX[]> WFGL_CXSLXX01(VO_WF_SLXX vo_WF_SLXX);
        Tuple<VOX_SYS_HEAD, VOX_SYS_ERROR, VO_WF_GZLDY[]> WFDY_CXLCDY(VO_WF_GZLDY vo_WF_GZLDY);
        Tuple<VOX_SYS_HEAD, VOX_SYS_ERROR, VO_WF_SLXX_CX[]> WFGL_CXSLXX_LS(VO_WF_SLXX_LS vo_WF_SLXX_LS);
        Tuple<VOX_SYS_HEAD, VOX_SYS_ERROR, VO_WF_SLTJ_CX[]> WFGL_SLTJ(VO_WF_SLTJ_CX vo_WF_SLTJ);
        Tuple<VOX_SYS_HEAD, VOX_SYS_ERROR, VO_WF_LZXX_LS[]> WFGL_CXLZXX_LS(VO_WF_LZXX_LS vo_WF_LZXX_LS);
        Tuple<VOX_SYS_HEAD, VOX_SYS_ERROR, VO_WF_LZXX[]> WFGL_CXLZXX(VO_WF_LZXX vo_WF_LZXX);
        Tuple<VOX_SYS_HEAD, VOX_SYS_ERROR, VO_WF_LZSXW[]> WFGL_CXLZSXW(VO_WF_LZSXW vo_WF_LZSXW);
        Tuple<VOX_SYS_HEAD, VOX_SYS_ERROR, VO_WF_SLXX> WFGL_SLCL(VO_WF_CZRZ vo_WF_CZRZ,VO_WF_SLXX vo_WF_SLXX,VO_WF_GZLHD vo_WF_GZLHD,VO_WF_LZSXW vo_WF_LZSXW);
    }
}
